// SPDX-FileCopyrightText: 2024 Shun Sakai
//
// SPDX-License-Identifier: CC0-1.0

= Public Data License in Lightweight Markup Languages
:da-url: https://www.digital.go.jp
:pdl10-url: {da-url}/resources/open_data/public_data_license_v1.0
:asciidoctor-url: https://asciidoctor.org/
:pandoc-url: https://pandoc.org/
:pdl10-pdf-url: {da-url}/assets/contents/node/basic_page/field_ref_resources/f7fde41d-ffca-4b2a-9b25-94b8a701a037/24afdf33/20240705_resources_data_outline_05.pdf
:pdl10-docx-url: {da-url}/assets/contents/node/basic_page/field_ref_resources/f7fde41d-ffca-4b2a-9b25-94b8a701a037/41722b25/20240705_resources_data_outline_06.docx
:pdl10-en-url: {da-url}/en/resources/open_data/public_data_license_v1.0
:pdl10-en-pdf-url: {da-url}/assets/contents/node/basic_page/field_ref_resources/f7fde41d-ffca-4b2a-9b25-94b8a701a037/3d15f10d/20241122_resource_open_data_01.pdf
:pdl10-en-docx-url: {da-url}/assets/contents/node/basic_page/field_ref_resources/f7fde41d-ffca-4b2a-9b25-94b8a701a037/2b1943f2/20241122_resource_open_data_01.docx
:reuse-spec-url: https://reuse.software/spec/

link:README.adoc[日本語]

The {pdl10-url}[*Public Data License (Version 1.0)*] is the terms of use
established by the Digital Agency on July 2024 for use by public institutions
such as the Government of Japan or local public entities. As of 24 December
2024, this is available as Web text, PDF or Word file. At this time, the
official document in Japanese and the reference translation in English are
available.

This project provides the terms of use written in lightweight markup languages
such as Markdown.

== Available formats

https://asciidoc.org/[AsciiDoc]::

  * link:assets/en/PDL-1.0.adoc[English version]
  * link:assets/ja/PDL-1.0.adoc[Japanese version]

https://commonmark.org/[CommonMark]::

  * link:assets/en/PDL-1.0.md[English version]
  * link:assets/ja/PDL-1.0.md[Japanese version]

=== Convert to other formats

These files can be converted to other formats using
{asciidoctor-url}[Asciidoctor] and {pandoc-url}[Pandoc].

.Convert AsciiDoc to HTML
[source,sh]
----
asciidoctor assets/ja/PDL-1.0.adoc
----

.Convert CommonMark to HTML
[source,sh]
----
pandoc -f commonmark -o PDL-1.0.html -s assets/ja/PDL-1.0.md
----

== Source code

The upstream repository is available at
https://github.com/sorairolake/public-data-license-lml.git.

.The source code is also available at
* https://gitlab.com/sorairolake/public-data-license-lml.git
* https://codeberg.org/sorairolake/public-data-license-lml.git

== Changelog

Please see link:CHANGELOG.adoc[].

== Contributing

Please see link:CONTRIBUTING.adoc[].

== Source

The source can be referred at {pdl10-url}. The terms of use is also available
as {pdl10-pdf-url}[PDF] or {pdl10-docx-url}[Word file].

The reference translation in English can be referred at {pdl10-en-url}. This is
also available as {pdl10-en-pdf-url}[PDF] or {pdl10-en-docx-url}[Word file].

== License

* Copyright (C) 2024 Digital Agency
* Copyright (C) 2024 Shun Sakai

. Unless otherwise noted, the contents of this repository are distributed under
  the terms of the _Creative Commons Attribution 4.0 International Public
  License_.
. In addition, some files are distributed under the terms of the _CC0 1.0
  Universal_.

The source is licensed under the
{pdl10-url}[_Public Data License (Version 1.0)_]. The Terms of Use are
compatible with the _CC BY 4.0 license_. For the terms of use of the source,
see https://www.digital.go.jp/copyright-policy.

This project is compliant with version 3.2 of the
{reuse-spec-url}[_REUSE Specification_]. See copyright notices of individual
files for more details on copyright and licensing information.
